In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
data = pd.read_csv('income-rent-bad.csv')
data

Income  Rent
0    2300   950
1    1400   500
2    2400  1000
3    5250  1800
4    4375  1600
5    1800   600
6    1500   500
7    1600   600
8    4150  1800
9    4500  1750

In [4]:
X = data[['Income']]
X

Income
0    2300
1    1400
2    2400
3    5250
4    4375
5    1800
6    1500
7    1600
8    4150
9    4500

In [5]:
y = data[['Rent']]
y

Rent
0   950
1   500
2  1000
3  1800
4  1600
5   600
6   500
7   600
8  1800
9  1750

In [6]:
# Create a Linear Regression Model
model = linear_model.LinearRegression()
model.fit(X,y)

LinearRegression()

In [7]:
model.coef_

array([[0.37755216]])

In [8]:
model.intercept_

array([4.71604235])

In [9]:
pred = model.predict(X)
pred

array([[ 873.08601762],
       [ 533.28907077],
       [ 910.84123393],
       [1986.86489894],
       [1656.50675617],
       [ 684.30993604],
       [ 571.04428709],
       [ 608.79950341],
       [1571.55751946],
       [1703.70077657]])

In [10]:
from sklearn.metrics import r2_score
r2_score(y, pred)

0.9587991788081074

In [11]:
model.predict([[4000]])

C:\Users\knsab\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1514.92469499]])