In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [3]:
# Read the dataset
data = pd.read_csv('insurance.csv')
data

age  have_insurance
0    22               0
1    25               0
2    47               1
3    52               0
4    46               1
5    56               1
6    63               0
7    60               1
8    62               1
9    61               1
10   18               0
11   28               0
12   27               0
13   29               0
14   49               1
15   23               0
16   35               0
17   55               1
18   54               0
19   48               1
20   58               1
21   45               0
22   66               1
23   65               1
24   59               1
25   20               0
26   31               0
27   33               0
28   39               0
29   50               1

In [4]:
X = data[['age']]
y = data[['have_insurance']]

In [5]:
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [7]:
model.coef_, model.intercept_

(array([[0.16759302]]), array([-7.93581903]))

In [8]:
pred = model.predict(X)
pred

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1])

In [9]:
data['Pred'] = pred
data

age  have_insurance  Pred
0    22               0     0
1    25               0     0
2    47               1     0
3    52               0     1
4    46               1     0
5    56               1     1
6    63               0     1
7    60               1     1
8    62               1     1
9    61               1     1
10   18               0     0
11   28               0     0
12   27               0     0
13   29               0     0
14   49               1     1
15   23               0     0
16   35               0     0
17   55               1     1
18   54               0     1
19   48               1     1
20   58               1     1
21   45               0     0
22   66               1     1
23   65               1     1
24   59               1     1
25   20               0     0
26   31               0     0
27   33               0     0
28   39               0     0
29   50               1     1

In [10]:
y_proba = model.predict_proba(X)
y_proba

array([[0.98591934, 0.01408066],
       [0.97693251, 0.02306749],
       [0.51473249, 0.48526751],
       [0.31453155, 0.68546845],
       [0.55639403, 0.44360597],
       [0.19009543, 0.80990457],
       [0.06770171, 0.93229829],
       [0.10719082, 0.89280918],
       [0.07907744, 0.92092256],
       [0.09217562, 0.90782438],
       [0.9927476 , 0.0072524 ],
       [0.96242852, 0.03757148],
       [0.96804059, 0.03195941],
       [0.95587588, 0.04412412],
       [0.43137607, 0.56862393],
       [0.98339292, 0.01660708],
       [0.88795926, 0.11204074],
       [0.21724446, 0.78275554],
       [0.24708794, 0.75291206],
       [0.47286518, 0.52713482],
       [0.14373898, 0.85626102],
       [0.59727725, 0.40272275],
       [0.04207481, 0.95792519],
       [0.04937256, 0.95062744],
       [0.12431702, 0.87568298],
       [0.9898889 , 0.0101111 ],
       [0.9393709 , 0.0606291 ],
       [0.91722672, 0.08277328],
       [0.80213488, 0.19786512],
       [0.39082825, 0.60917175]])

In [11]:
metrics.accuracy_score(y , pred)

0.8333333333333334

In [12]:
metrics.confusion_matrix(y , pred)

array([[13,  3],
       [ 2, 12]])